--- #YAML:1.0
name:                Bot-BasicBot-Pluggable-Module-Twitter
version:             0.0.3
abstract:            Post message to twitter
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Bot::BasicBot::Pluggable::Module: 0
    Net::Twitter:                  0
    Test::More:                    0
    Test::Perl::Critic:            0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - franck cuny <franck.cuny@gmail.com>
